<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogAccesRepository extends EntityRepository
{
}
